name: Build and Publish

on:
    push:
      branches:
        - master
      tags:
        - '*'
    workflow_dispatch:
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14.17.0
        uses: actions/setup-node@v1
        with:
         node-version: v14.17.0
      - name: Install dependencies
        run: npm install
      - name: Run test command
        run: npm run test  
      - name: Run bundle commands
        run: npm run bundle
      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm publish --new-version $(jq -r ".version" package.json)